Allow secure cookies for localhost
snoyberg/http-client pull request #460
Opened 2021-04-12 18:55 UTC by mulderr

Closes #459

Up for review. Still testing.

2021-04-13 05:15 UTC, snoyberg requested changes

2021-04-13 05:15 UTC, snoyberg commented on http-client/Network/HTTP/Client/Cookies.hs
> +          fmap (head . IP.fromIPv4) (readMaybe (S8.unpack host)) == Just 127
I'm uncomfortable about usage of a partial function here, `take 1` would be better

2021-04-13 07:47 UTC, mulderr commented
I've noticed `Read` instances for [`IPv4`](http://hackage.haskell.org/package/iproute-1.7.11/docs/src/Data.IP.Addr.html#ip4) and [`IPv6`](http://hackage.haskell.org/package/iproute-1.7.11/docs/src/Data.IP.Addr.html#ip6) skip leading whitespace. Not sure if this creates any real issues but just to be safe I'd rather refactor to use the parsers directly and be as strict as possible.

2021-04-13 14:24 UTC, mulderr commented
On the other hand it's already parsed by network-uri and it's an internal function therefore I guess it's fine. Let me now if you'd prefer a stricter version.

2021-04-14 07:17 UTC, snoyberg commented
I'm OK with this as-is. Have you finished your testing? Is this ready for final review?

2021-04-14 07:50 UTC, mulderr commented
Yep! Looks good but I'm of course happy to fix any remaining issues.

2021-04-14 10:42 UTC, snoyberg commented
Only other thing is some bookkeeping. Please:

* Perform a minor version bump in the .cabal file
* Add a ChangeLog entry

2021-04-14 11:46 UTC, snoyberg approved these changes
Thank you!

2021-04-14 11:47 UTC, merged