Adds `shouldStripHeaderOnRedirectIfOnDifferentHostOnly` option on `Request`
snoyberg/http-client pull request #520
Opened 2023-10-19 19:50 UTC by meghfossa

### Overview
This PR, 
- adds `shouldStripHeaderOnRedirectIfOnDifferentHostOnly` option to `Request`
- modifies `getRedirectedRequest` signature to include original `Request`

### Why?

Many stdlib in other language and ecosystem offer this functionality by default - refer to `golang` and `python-requests` for  example. Potentially leaking headers to different host can lead to security incident. Refer to Python's CVE re this: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20060

Ideally, `shouldStripHeaderOnRedirect` should have only stripped headers if the host differed, so without breaking change, this seems to be second best option.

### Testing

- I added few automated tests.

### Remaining 

- [ ] Anything else is needed for contribution or release?

2023-10-19 19:51 UTC, meghfossa commented
Hi @snoyberg, let me know what I can do to get this to finish line!

2023-10-24 11:26 UTC, snoyberg requested changes
Seems reasonable. Can you add a minor version bump and changelog entry? Also, please bump the `@since` comment to match the new version.

2023-10-30 05:33 UTC, snoyberg approved these changes

2023-10-30 08:14 UTC, merged

2023-10-30 08:15 UTC, snoyberg commented
Thanks! Released to Hackage.